### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tbhDequan** [TheAz928/VanillaEnchantments#25] opened 2017-12-16 19:55 UTC
16.12 14:55:11 [Server] Server thread/CRITICAL Error: "Undefined class constant 'CAUSE_EXPLOSION'" (EXCEPTION) in "VanillaEnchantments_v2.0.0-dev/src/VanillaEnchantments/handlers/BlastProtection" at line 22

**Comment by inxomnyaa** [comment] 2017-12-17 02:26
duplicate of https://github.com/TheAz928/VanillaEnchantments/issues/18

**Closed as completed** 2017-12-26 13:18 UTC
